
[[keyboard.bindings]]
key = "F11"

[keyboard.bindings.command]
program = "fullscreen"

[colors.primary]
background = "#010B17"
foreground = "#EBDDF4"

[cursor.style]
blinking = "On"

[font]
size = 13.0
# normal = { family = "JetBrainsMono Nerd Font" }
normal = { family = "JetBrainsMono NF" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
bold_italic = { family = "JetBrainsMono Nerd Font" }

[scrolling]
history = 10000

[window]
# decorations = "none"
opacity = 0.98
title = ""

[window.padding]
x = 8
y = 2

[window.dimensions]
columns = 150
lines = 34

[keyboard]

[env]
TERM = "xterm-256color"
