
[[keyboard.bindings]]
key = "F11"

[keyboard.bindings.command]
program = "fullscreen"

[colors.primary]
background = "#010B17"
foreground = "#EBDDF4"

[cursor.style]
blinking = "On"

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 10000

[window]
# decorations = "none"
opacity = 0.98
title = ""

[window.padding]
x = 8
y = 2

[window.dimensions]
columns = 150
lines = 34

[keyboard]
