# Change the prefix key to C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set-option -g focus-events on

set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:RGB"

set -g base-index 1          # start indexing windows at 1 instead of 0
set -g detach-on-destroy off # don't exit from tmux when closing a session
set -g escape-time 0         # zero-out escape time delay
set -g history-limit 1000000 # increase history size (from 2,000)
set -g mouse on              # enable mouse support
set -g renumber-windows on   # renumber all windows when any window is closed
set -g set-clipboard on      # use system clipboard
set -g status-interval 3     # update the status bar every 3 seconds

set -g status-left "#[fg=colour10,bold] #S"
set -g status-left-length 200
set -g status-position top
set -g status-right '#[fg=white#,bg=purple]#{?window_zoomed_flag, Z ,}#[default,fg=green] #{window_panes}'
set -g status-style 'bg=default' # transparent

set -g window-status-current-format '#[fg=colour51]   #[fg=colour14]#W'
set -g window-status-format '  #[fg=gray]#W'
set -g message-command-style 'bg=default,fg=yellow'
set -g message-style 'bg=default,fg=yellow'
set -g mode-style 'bg=default,fg=yellow'
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'
set -g status-keys vi
set -g mode-keys vi

# pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# reload source file
bind-key R source-file ~/.config/tmux/tmux.conf \; display "Reloaded .tmux.config"
